#server:
#  port: 8443
#  ssl:
#    key-store: classpath:mykeys.p12
#    key-store-password: letmein
#    key-password: letmein
spring:
  datasource:
    driverClassName: "org.h2.Driver"
    url: "jdbc:h2:mem:tacocloud"
    username: sa
    password: sa

#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/tacocloud
#    username: root
#    password: exampledb20

#  sql:
#    init:
#      mode: always
#      schema-locations: classpath:schema.sql
##      data-locations:

#logging:
#  level:
#    root: WARN
#    org:
#      Springframework:
#        security: DEBUG
#    org.springframework.security: DEBUG
